version: "0.1"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
        - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code:consistent
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_SECRET=!@$&^*($234967weruifl:"|}{`kgfj;lKJVNXCM<>JKSLEUIR3458345IOUPSDF::|L"E}W{#*(@$&%#+
      - DJANGO_DEBUG=False
      - DJANGO_HOSTS=*
      - DJANGO_SECURE=False
    depends_on:
      - db