# Generated by Django 4.1.2 on 2022-12-26 03:22

from django.db import migrations
import sys
sys.path.append('../../')
import load_db


class Migration(migrations.Migration):

    dependencies = [
        ('restify', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_db.populate_database)
    ]
